module.exports = {
    elementsList: [
	{
	    name: "Hydrogen",
	    appearance: "colorless gas",
	    atomic_mass: 1.008,
	    boil: 20.271,
	    category: "alkali",
	    color: null,
	    density: 0.08988,
	    discovered_by: "Henry Cavendish",
	    melt: 13.99,
	    molar_heat: 28.836,
	    named_by: "Antoine Lavoisier",
	    number: 1,
	    period: 1,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Hydrogen",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Hydrogen_Spectra.jpg",
	    symbol: "H",
	    xpos: 1,
	    ypos: 1,
	    shells: [
		1
	    ]
	},
	{
	    name: "Helium",
	    appearance: "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
	    atomic_mass: 4.0026022,
	    boil: 4.222,
	    category: "noble gas",
	    color: null,
	    density: 0.1786,
	    discovered_by: "Pierre Janssen",
	    melt: 0.95,
	    molar_heat: null,
	    named_by: null,
	    number: 2,
	    period: 1,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Helium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Helium_spectrum.jpg",
	    symbol: "He",
	    xpos: 18,
	    ypos: 1,
	    shells: [
		2
	    ]
	},
	{
	    name: "Lithium",
	    appearance: "silvery-white",
	    atomic_mass: 6.94,
	    boil: 1603,
	    category: "alkali",
	    color: null,
	    density: 0.534,
	    discovered_by: "Johan August Arfwedson",
	    melt: 453.65,
	    molar_heat: 24.86,
	    named_by: null,
	    number: 3,
	    period: 2,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Lithium",
	    spectral_img: null,
	    symbol: "Li",
	    xpos: 1,
	    ypos: 2,
	    shells: [
		2,
		1
	    ]
	},
	{
	    name: "Beryllium",
	    appearance: "white-gray metallic",
	    atomic_mass: 9.01218315,
	    boil: 2742,
	    category: "alkaline earth metal",
	    color: null,
	    density: 1.85,
	    discovered_by: "Louis Nicolas Vauquelin",
	    melt: 1560,
	    molar_heat: 16.443,
	    named_by: null,
	    number: 4,
	    period: 2,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Beryllium",
	    spectral_img: null,
	    symbol: "Be",
	    xpos: 2,
	    ypos: 2,
	    shells: [
		2,
		2
	    ]
	},
	{
	    name: "Boron",
	    appearance: "black-brown",
	    atomic_mass: 10.81,
	    boil: 4200,
	    category: "metalloid",
	    color: null,
	    density: 2.08,
	    discovered_by: "Joseph Louis Gay-Lussac",
	    melt: 2349,
	    molar_heat: 11.087,
	    named_by: null,
	    number: 5,
	    period: 2,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Boron",
	    spectral_img: null,
	    symbol: "B",
	    xpos: 13,
	    ypos: 2,
	    shells: [
		2,
		3
	    ]
	},
	{
	    name: "Carbon",
	    appearance: null,
	    atomic_mass: 12.011,
	    boil: null,
	    category: "polyatomic nonmetal",
	    color: null,
	    density: 1.821,
	    discovered_by: "Ancient Egypt",
	    melt: null,
	    molar_heat: 8.517,
	    named_by: null,
	    number: 6,
	    period: 2,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Carbon",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Carbon_Spectra.jpg",
	    symbol: "C",
	    xpos: 14,
	    ypos: 2,
	    shells: [
		2,
		4
	    ]
	},
	{
	    name: "Nitrogen",
	    appearance: "colorless gas, liquid or solid",
	    atomic_mass: 14.007,
	    boil: 77.355,
	    category: "diatomic nonmetal",
	    color: null,
	    density: 1.251,
	    discovered_by: "Daniel Rutherford",
	    melt: 63.15,
	    molar_heat: null,
	    named_by: "Jean-Antoine Chaptal",
	    number: 7,
	    period: 2,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Nitrogen",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Nitrogen_Spectra.jpg",
	    symbol: "N",
	    xpos: 15,
	    ypos: 2,
	    shells: [
		2,
		5
	    ]
	},
	{
	    name: "Oxygen",
	    appearance: null,
	    atomic_mass: 15.999,
	    boil: 90.188,
	    category: "diatomic nonmetal",
	    color: null,
	    density: 1.429,
	    discovered_by: "Carl Wilhelm Scheele",
	    melt: 54.36,
	    molar_heat: null,
	    named_by: "Antoine Lavoisier",
	    number: 8,
	    period: 2,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Oxygen",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Oxygen_spectre.jpg",
	    symbol: "O",
	    xpos: 16,
	    ypos: 2,
	    shells: [
		2,
		6
	    ]
	},
	{
	    name: "Fluorine",
	    appearance: null,
	    atomic_mass: 18.9984031636,
	    boil: 85.03,
	    category: "diatomic nonmetal",
	    color: null,
	    density: 1.696,
	    discovered_by: "André-Marie Ampère",
	    melt: 53.48,
	    molar_heat: null,
	    named_by: "Humphry Davy",
	    number: 9,
	    period: 2,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Fluorine",
	    spectral_img: null,
	    symbol: "F",
	    xpos: 17,
	    ypos: 2,
	    shells: [
		2,
		7
	    ]
	},
	{
	    name: "Neon",
	    appearance: "colorless gas exhibiting an orange-red glow when placed in a high voltage electric field",
	    atomic_mass: 20.17976,
	    boil: 27.104,
	    category: "noble gas",
	    color: null,
	    density: 0.9002,
	    discovered_by: "Morris Travers",
	    melt: 24.56,
	    molar_heat: null,
	    named_by: null,
	    number: 10,
	    period: 2,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Neon",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Neon_spectra.jpg",
	    symbol: "Ne",
	    xpos: 18,
	    ypos: 2,
	    shells: [
		2,
		8
	    ]
	},
	{
	    name: "Sodium",
	    appearance: "silvery white metallic",
	    atomic_mass: 22.989769282,
	    boil: 1156.09,
	    category: "alkali",
	    color: null,
	    density: 0.968,
	    discovered_by: "Humphry Davy",
	    melt: 370.944,
	    molar_heat: 28.23,
	    named_by: null,
	    number: 11,
	    period: 3,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Sodium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Sodium_Spectra.jpg",
	    symbol: "Na",
	    xpos: 1,
	    ypos: 3,
	    shells: [
		2,
		8,
		1
	    ]
	},
	{
	    name: "Magnesium",
	    appearance: "shiny grey solid",
	    atomic_mass: 24.305,
	    boil: 1363,
	    category: "alkaline earth metal",
	    color: null,
	    density: 1.738,
	    discovered_by: "Joseph Black",
	    melt: 923,
	    molar_heat: 24.869,
	    named_by: null,
	    number: 12,
	    period: 3,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Magnesium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Magnesium_Spectra.jpg",
	    symbol: "Mg",
	    xpos: 2,
	    ypos: 3,
	    shells: [
		2,
		8,
		2
	    ]
	},
	{
	    name: "Aluminium",
	    appearance: "silvery gray metallic",
	    atomic_mass: 26.98153857,
	    boil: 2743,
	    category: "post-transition metal",
	    color: null,
	    density: 2.7,
	    discovered_by: null,
	    melt: 933.47,
	    molar_heat: 24.2,
	    named_by: "Humphry Davy",
	    number: 13,
	    period: 3,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Aluminium",
	    spectral_img: null,
	    symbol: "Al",
	    xpos: 13,
	    ypos: 3,
	    shells: [
		2,
		8,
		3
	    ]
	},
	{
	    name: "Silicon",
	    appearance: "crystalline, reflective with bluish-tinged faces",
	    atomic_mass: 28.085,
	    boil: 3538,
	    category: "metalloid",
	    color: null,
	    density: 2.329,
	    discovered_by: "Jöns Jacob Berzelius",
	    melt: 1687,
	    molar_heat: 19.789,
	    named_by: "Thomas Thomson (chemist)",
	    number: 14,
	    period: 3,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Silicon",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Silicon_Spectra.jpg",
	    symbol: "Si",
	    xpos: 14,
	    ypos: 3,
	    shells: [
		2,
		8,
		4
	    ]
	},
	{
	    name: "Phosphorus",
	    appearance: "colourless, waxy white, yellow, scarlet, red, violet, black",
	    atomic_mass: 30.9737619985,
	    boil: null,
	    category: "polyatomic nonmetal",
	    color: null,
	    density: 1.823,
	    discovered_by: "Hennig Brand",
	    melt: null,
	    molar_heat: 23.824,
	    named_by: null,
	    number: 15,
	    period: 3,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Phosphorus",
	    spectral_img: null,
	    symbol: "P",
	    xpos: 15,
	    ypos: 3,
	    shells: [
		2,
		8,
		5
	    ]
	},
	{
	    name: "Sulfur",
	    appearance: "lemon yellow sintered microcrystals",
	    atomic_mass: 32.06,
	    boil: 717.8,
	    category: "polyatomic nonmetal",
	    color: null,
	    density: 2.07,
	    discovered_by: "Ancient china",
	    melt: 388.36,
	    molar_heat: 22.75,
	    named_by: null,
	    number: 16,
	    period: 3,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Sulfur",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Sulfur_Spectrum.jpg",
	    symbol: "S",
	    xpos: 16,
	    ypos: 3,
	    shells: [
		2,
		8,
		6
	    ]
	},
	{
	    name: "Chlorine",
	    appearance: "pale yellow-green gas",
	    atomic_mass: 35.45,
	    boil: 239.11,
	    category: "diatomic nonmetal",
	    color: null,
	    density: 3.2,
	    discovered_by: "Carl Wilhelm Scheele",
	    melt: 171.6,
	    molar_heat: null,
	    named_by: null,
	    number: 17,
	    period: 3,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Chlorine",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Chlorine_spectrum_visible.png",
	    symbol: "Cl",
	    xpos: 17,
	    ypos: 3,
	    shells: [
		2,
		8,
		7
	    ]
	},
	{
	    name: "Argon",
	    appearance: "colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field",
	    atomic_mass: 39.9481,
	    boil: 87.302,
	    category: "noble gas",
	    color: null,
	    density: 1.784,
	    discovered_by: "Lord Rayleigh",
	    melt: 83.81,
	    molar_heat: null,
	    named_by: null,
	    number: 18,
	    period: 3,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Argon",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Argon_Spectrum.png",
	    symbol: "Ar",
	    xpos: 18,
	    ypos: 3,
	    shells: [
		2,
		8,
		8
	    ]
	},
	{
	    name: "Potassium",
	    appearance: "silvery gray",
	    atomic_mass: 39.09831,
	    boil: 1032,
	    category: "alkali",
	    color: null,
	    density: 0.862,
	    discovered_by: "Humphry Davy",
	    melt: 336.7,
	    molar_heat: 29.6,
	    named_by: null,
	    number: 19,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Potassium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Potassium_Spectrum.jpg",
	    symbol: "K",
	    xpos: 1,
	    ypos: 4,
	    shells: [
		2,
		8,
		8,
		1
	    ]
	},
	{
	    name: "Calcium",
	    appearance: null,
	    atomic_mass: 40.0784,
	    boil: 1757,
	    category: "alkaline earth metal",
	    color: null,
	    density: 1.55,
	    discovered_by: "Humphry Davy",
	    melt: 1115,
	    molar_heat: 25.929,
	    named_by: null,
	    number: 20,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Calcium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Calcium_Spectrum.png",
	    symbol: "Ca",
	    xpos: 2,
	    ypos: 4,
	    shells: [
		2,
		8,
		8,
		2
	    ]
	},
	{
	    name: "Scandium",
	    appearance: "silvery white",
	    atomic_mass: 44.9559085,
	    boil: 3109,
	    category: "transition metal",
	    color: null,
	    density: 2.985,
	    discovered_by: "Lars Fredrik Nilson",
	    melt: 1814,
	    molar_heat: 25.52,
	    named_by: null,
	    number: 21,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Scandium",
	    spectral_img: null,
	    symbol: "Sc",
	    xpos: 3,
	    ypos: 4,
	    shells: [
		2,
		8,
		9,
		2
	    ]
	},
	{
	    name: "Titanium",
	    appearance: "silvery grey-white metallic",
	    atomic_mass: 47.8671,
	    boil: 3560,
	    category: "transition metal",
	    color: null,
	    density: 4.506,
	    discovered_by: "William Gregor",
	    melt: 1941,
	    molar_heat: 25.06,
	    named_by: "Martin Heinrich Klaproth",
	    number: 22,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Titanium",
	    spectral_img: null,
	    symbol: "Ti",
	    xpos: 4,
	    ypos: 4,
	    shells: [
		2,
		8,
		10,
		2
	    ]
	},
	{
	    name: "Vanadium",
	    appearance: "blue-silver-grey metal",
	    atomic_mass: 50.94151,
	    boil: 3680,
	    category: "transition metal",
	    color: null,
	    density: 6,
	    discovered_by: "Andrés Manuel del Río",
	    melt: 2183,
	    molar_heat: 24.89,
	    named_by: "Isotopes of vanadium",
	    number: 23,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Vanadium",
	    spectral_img: null,
	    symbol: "V",
	    xpos: 5,
	    ypos: 4,
	    shells: [
		2,
		8,
		11,
		2
	    ]
	},
	{
	    name: "Chromium",
	    appearance: "silvery metallic",
	    atomic_mass: 51.99616,
	    boil: 2944,
	    category: "transition metal",
	    color: null,
	    density: 7.19,
	    discovered_by: "Louis Nicolas Vauquelin",
	    melt: 2180,
	    molar_heat: 23.35,
	    named_by: null,
	    number: 24,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Chromium",
	    spectral_img: null,
	    symbol: "Cr",
	    xpos: 6,
	    ypos: 4,
	    shells: [
		2,
		8,
		13,
		1
	    ]
	},
	{
	    name: "Manganese",
	    appearance: "silvery metallic",
	    atomic_mass: 54.9380443,
	    boil: 2334,
	    category: "transition metal",
	    color: null,
	    density: 7.21,
	    discovered_by: "Torbern Olof Bergman",
	    melt: 1519,
	    molar_heat: 26.32,
	    named_by: null,
	    number: 25,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Manganese",
	    spectral_img: null,
	    symbol: "Mn",
	    xpos: 7,
	    ypos: 4,
	    shells: [
		2,
		8,
		13,
		2
	    ]
	},
	{
	    name: "Iron",
	    appearance: "lustrous metallic with a grayish tinge",
	    atomic_mass: 55.8452,
	    boil: 3134,
	    category: "transition metal",
	    color: null,
	    density: 7.874,
	    discovered_by: "5000 BC",
	    melt: 1811,
	    molar_heat: 25.1,
	    named_by: null,
	    number: 26,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Iron",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Iron_Spectrum.jpg",
	    symbol: "Fe",
	    xpos: 8,
	    ypos: 4,
	    shells: [
		2,
		8,
		14,
		2
	    ]
	},
	{
	    name: "Cobalt",
	    appearance: "hard lustrous gray metal",
	    atomic_mass: 58.9331944,
	    boil: 3200,
	    category: "transition metal",
	    color: "metallic gray",
	    density: 8.9,
	    discovered_by: "Georg Brandt",
	    melt: 1768,
	    molar_heat: 24.81,
	    named_by: null,
	    number: 27,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Cobalt",
	    spectral_img: null,
	    symbol: "Co",
	    xpos: 9,
	    ypos: 4,
	    shells: [
		2,
		8,
		15,
		2
	    ]
	},
	{
	    name: "Nickel",
	    appearance: "lustrous, metallic, and silver with a gold tinge",
	    atomic_mass: 58.69344,
	    boil: 3003,
	    category: "transition metal",
	    color: null,
	    density: 8.908,
	    discovered_by: "Axel Fredrik Cronstedt",
	    melt: 1728,
	    molar_heat: 26.07,
	    named_by: null,
	    number: 28,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Nickel",
	    spectral_img: null,
	    symbol: "Ni",
	    xpos: 10,
	    ypos: 4,
	    shells: [
		2,
		8,
		16,
		2
	    ]
	},
	{
	    name: "Copper",
	    appearance: "red-orange metallic luster",
	    atomic_mass: 63.5463,
	    boil: 2835,
	    category: "transition metal",
	    color: null,
	    density: 8.96,
	    discovered_by: "Middle East",
	    melt: 1357.77,
	    molar_heat: 24.44,
	    named_by: null,
	    number: 29,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Copper",
	    spectral_img: null,
	    symbol: "Cu",
	    xpos: 11,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		1
	    ]
	},
	{
	    name: "Zinc",
	    appearance: "silver-gray",
	    atomic_mass: 65.382,
	    boil: 1180,
	    category: "transition metal",
	    color: null,
	    density: 7.14,
	    discovered_by: "India",
	    melt: 692.68,
	    molar_heat: 25.47,
	    named_by: null,
	    number: 30,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Zinc",
	    spectral_img: null,
	    symbol: "Zn",
	    xpos: 12,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		2
	    ]
	},
	{
	    name: "Gallium",
	    appearance: "silver-white",
	    atomic_mass: 69.7231,
	    boil: 2673,
	    category: "post-transition metal",
	    color: null,
	    density: 5.91,
	    discovered_by: "Lecoq de Boisbaudran",
	    melt: 302.9146,
	    molar_heat: 25.86,
	    named_by: null,
	    number: 31,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Gallium",
	    spectral_img: null,
	    symbol: "Ga",
	    xpos: 13,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		3
	    ]
	},
	{
	    name: "Germanium",
	    appearance: "grayish-white",
	    atomic_mass: 72.6308,
	    boil: 3106,
	    category: "metalloid",
	    color: null,
	    density: 5.323,
	    discovered_by: "Clemens Winkler",
	    melt: 1211.4,
	    molar_heat: 23.222,
	    named_by: null,
	    number: 32,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Germanium",
	    spectral_img: null,
	    symbol: "Ge",
	    xpos: 14,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		4
	    ]
	},
	{
	    name: "Arsenic",
	    appearance: "metallic grey",
	    atomic_mass: 74.9215956,
	    boil: null,
	    category: "metalloid",
	    color: null,
	    density: 5.727,
	    discovered_by: "Bronze Age",
	    melt: null,
	    molar_heat: 24.64,
	    named_by: null,
	    number: 33,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Arsenic",
	    spectral_img: null,
	    symbol: "As",
	    xpos: 15,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		5
	    ]
	},
	{
	    name: "Selenium",
	    appearance: "black, red, and gray (not pictured) allotropes",
	    atomic_mass: 78.9718,
	    boil: 958,
	    category: "polyatomic nonmetal",
	    color: null,
	    density: 4.81,
	    discovered_by: "Jöns Jakob Berzelius",
	    melt: 494,
	    molar_heat: 25.363,
	    named_by: null,
	    number: 34,
	    period: 4,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Selenium",
	    spectral_img: null,
	    symbol: "Se",
	    xpos: 16,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		6
	    ]
	},
	{
	    name: "Bromine",
	    appearance: null,
	    atomic_mass: 79.904,
	    boil: 332,
	    category: "diatomic nonmetal",
	    color: null,
	    density: 3.1028,
	    discovered_by: "Antoine Jérôme Balard",
	    melt: 265.8,
	    molar_heat: null,
	    named_by: null,
	    number: 35,
	    period: 4,
	    phase: "Liquid",
	    source: "https://en.wikipedia.org/wiki/Bromine",
	    spectral_img: null,
	    symbol: "Br",
	    xpos: 17,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		7
	    ]
	},
	{
	    name: "Krypton",
	    appearance: "colorless gas, exhibiting a whitish glow in a high electric field",
	    atomic_mass: 83.7982,
	    boil: 119.93,
	    category: "noble gas",
	    color: null,
	    density: 3.749,
	    discovered_by: "William Ramsay",
	    melt: 115.78,
	    molar_heat: null,
	    named_by: null,
	    number: 36,
	    period: 4,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Krypton",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Krypton_Spectrum.jpg",
	    symbol: "Kr",
	    xpos: 18,
	    ypos: 4,
	    shells: [
		2,
		8,
		18,
		8
	    ]
	},
	{
	    name: "Rubidium",
	    appearance: "grey white",
	    atomic_mass: 85.46783,
	    boil: 961,
	    category: "alkali",
	    color: null,
	    density: 1.532,
	    discovered_by: "Robert Bunsen",
	    melt: 312.45,
	    molar_heat: 31.06,
	    named_by: null,
	    number: 37,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Rubidium",
	    spectral_img: null,
	    symbol: "Rb",
	    xpos: 1,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		8,
		1
	    ]
	},
	{
	    name: "Strontium",
	    appearance: null,
	    atomic_mass: 87.621,
	    boil: 1650,
	    category: "alkaline earth metal",
	    color: null,
	    density: 2.64,
	    discovered_by: "William Cruickshank (chemist)",
	    melt: 1050,
	    molar_heat: 26.4,
	    named_by: null,
	    number: 38,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Strontium",
	    spectral_img: null,
	    symbol: "Sr",
	    xpos: 2,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		8,
		2
	    ]
	},
	{
	    name: "Yttrium",
	    appearance: "silvery white",
	    atomic_mass: 88.905842,
	    boil: 3203,
	    category: "transition metal",
	    color: null,
	    density: 4.472,
	    discovered_by: "Johan Gadolin",
	    melt: 1799,
	    molar_heat: 26.53,
	    named_by: null,
	    number: 39,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Yttrium",
	    spectral_img: null,
	    symbol: "Y",
	    xpos: 3,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		9,
		2
	    ]
	},
	{
	    name: "Zirconium",
	    appearance: "silvery white",
	    atomic_mass: 91.2242,
	    boil: 4650,
	    category: "transition metal",
	    color: null,
	    density: 6.52,
	    discovered_by: "Martin Heinrich Klaproth",
	    melt: 2128,
	    molar_heat: 25.36,
	    named_by: null,
	    number: 40,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Zirconium",
	    spectral_img: null,
	    symbol: "Zr",
	    xpos: 4,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		10,
		2
	    ]
	},
	{
	    name: "Niobium",
	    appearance: "gray metallic, bluish when oxidized",
	    atomic_mass: 92.906372,
	    boil: 5017,
	    category: "transition metal",
	    color: null,
	    density: 8.57,
	    discovered_by: "Charles Hatchett",
	    melt: 2750,
	    molar_heat: 24.6,
	    named_by: null,
	    number: 41,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Niobium",
	    spectral_img: null,
	    symbol: "Nb",
	    xpos: 5,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		12,
		1
	    ]
	},
	{
	    name: "Molybdenum",
	    appearance: "gray metallic",
	    atomic_mass: 95.951,
	    boil: 4912,
	    category: "transition metal",
	    color: null,
	    density: 10.28,
	    discovered_by: "Carl Wilhelm Scheele",
	    melt: 2896,
	    molar_heat: 24.06,
	    named_by: null,
	    number: 42,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Molybdenum",
	    spectral_img: null,
	    symbol: "Mo",
	    xpos: 6,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		13,
		1
	    ]
	},
	{
	    name: "Technetium",
	    appearance: "shiny gray metal",
	    atomic_mass: 98,
	    boil: 4538,
	    category: "transition metal",
	    color: null,
	    density: 11,
	    discovered_by: "Emilio Segrè",
	    melt: 2430,
	    molar_heat: 24.27,
	    named_by: null,
	    number: 43,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Technetium",
	    spectral_img: null,
	    symbol: "Tc",
	    xpos: 7,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		13,
		2
	    ]
	},
	{
	    name: "Ruthenium",
	    appearance: "silvery white metallic",
	    atomic_mass: 101.072,
	    boil: 4423,
	    category: "transition metal",
	    color: null,
	    density: 12.45,
	    discovered_by: "Karl Ernst Claus",
	    melt: 2607,
	    molar_heat: 24.06,
	    named_by: null,
	    number: 44,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Ruthenium",
	    spectral_img: null,
	    symbol: "Ru",
	    xpos: 8,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		15,
		1
	    ]
	},
	{
	    name: "Rhodium",
	    appearance: "silvery white metallic",
	    atomic_mass: 102.905502,
	    boil: 3968,
	    category: "transition metal",
	    color: null,
	    density: 12.41,
	    discovered_by: "William Hyde Wollaston",
	    melt: 2237,
	    molar_heat: 24.98,
	    named_by: null,
	    number: 45,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Rhodium",
	    spectral_img: null,
	    symbol: "Rh",
	    xpos: 9,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		16,
		1
	    ]
	},
	{
	    name: "Palladium",
	    appearance: "silvery white",
	    atomic_mass: 106.421,
	    boil: 3236,
	    category: "transition metal",
	    color: null,
	    density: 12.023,
	    discovered_by: "William Hyde Wollaston",
	    melt: 1828.05,
	    molar_heat: 25.98,
	    named_by: null,
	    number: 46,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Palladium",
	    spectral_img: null,
	    symbol: "Pd",
	    xpos: 10,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18
	    ]
	},
	{
	    name: "Silver",
	    appearance: "lustrous white metal",
	    atomic_mass: 107.86822,
	    boil: 2435,
	    category: "transition metal",
	    color: null,
	    density: 10.49,
	    discovered_by: "unknown, before 5000 BC",
	    melt: 1234.93,
	    molar_heat: 25.35,
	    named_by: null,
	    number: 47,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Silver",
	    spectral_img: null,
	    symbol: "Ag",
	    xpos: 11,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		1
	    ]
	},
	{
	    name: "Cadmium",
	    appearance: "silvery bluish-gray metallic",
	    atomic_mass: 112.4144,
	    boil: 1040,
	    category: "transition metal",
	    color: null,
	    density: 8.65,
	    discovered_by: "Karl Samuel Leberecht Hermann",
	    melt: 594.22,
	    molar_heat: 26.02,
	    named_by: "Isotopes of cadmium",
	    number: 48,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Cadmium",
	    spectral_img: null,
	    symbol: "Cd",
	    xpos: 12,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		2
	    ]
	},
	{
	    name: "Indium",
	    appearance: "silvery lustrous gray",
	    atomic_mass: 114.8181,
	    boil: 2345,
	    category: "post-transition metal",
	    color: null,
	    density: 7.31,
	    discovered_by: "Ferdinand Reich",
	    melt: 429.7485,
	    molar_heat: 26.74,
	    named_by: null,
	    number: 49,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Indium",
	    spectral_img: null,
	    symbol: "In",
	    xpos: 13,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		3
	    ]
	},
	{
	    name: "Tin",
	    appearance: "silvery-white (beta, β) or gray (alpha, α)",
	    atomic_mass: 118.7107,
	    boil: 2875,
	    category: "post-transition metal",
	    color: null,
	    density: 7.365,
	    discovered_by: "unknown, before 3500 BC",
	    melt: 505.08,
	    molar_heat: 27.112,
	    named_by: null,
	    number: 50,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Tin",
	    spectral_img: null,
	    symbol: "Sn",
	    xpos: 14,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		4
	    ]
	},
	{
	    name: "Antimony",
	    appearance: "silvery lustrous gray",
	    atomic_mass: 121.7601,
	    boil: 1908,
	    category: "metalloid",
	    color: null,
	    density: 6.697,
	    discovered_by: "unknown, before 3000 BC",
	    melt: 903.78,
	    molar_heat: 25.23,
	    named_by: null,
	    number: 51,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Antimony",
	    spectral_img: null,
	    symbol: "Sb",
	    xpos: 15,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		5
	    ]
	},
	{
	    name: "Tellurium",
	    appearance: null,
	    atomic_mass: 127.603,
	    boil: 1261,
	    category: "metalloid",
	    color: null,
	    density: 6.24,
	    discovered_by: "Franz-Joseph Müller von Reichenstein",
	    melt: 722.66,
	    molar_heat: 25.73,
	    named_by: null,
	    number: 52,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Tellurium",
	    spectral_img: null,
	    symbol: "Te",
	    xpos: 16,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		6
	    ]
	},
	{
	    name: "Iodine",
	    appearance: "lustrous metallic gray, violet as a gas",
	    atomic_mass: 126.904473,
	    boil: 457.4,
	    category: "diatomic nonmetal",
	    color: null,
	    density: 4.933,
	    discovered_by: "Bernard Courtois",
	    melt: 386.85,
	    molar_heat: null,
	    named_by: null,
	    number: 53,
	    period: 5,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Iodine",
	    spectral_img: null,
	    symbol: "I",
	    xpos: 17,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		7
	    ]
	},
	{
	    name: "Xenon",
	    appearance: "colorless gas, exhibiting a blue glow when placed in a high voltage electric field",
	    atomic_mass: 131.2936,
	    boil: 165.051,
	    category: "noble gas",
	    color: null,
	    density: 5.894,
	    discovered_by: "William Ramsay",
	    melt: 161.4,
	    molar_heat: null,
	    named_by: null,
	    number: 54,
	    period: 5,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Xenon",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Xenon_Spectrum.jpg",
	    symbol: "Xe",
	    xpos: 18,
	    ypos: 5,
	    shells: [
		2,
		8,
		18,
		18,
		8
	    ]
	},
	{
	    name: "Cesium",
	    appearance: "silvery gold",
	    atomic_mass: 132.905451966,
	    boil: 944,
	    category: "alkali",
	    color: null,
	    density: 1.93,
	    discovered_by: "Robert Bunsen",
	    melt: 301.7,
	    molar_heat: 32.21,
	    named_by: null,
	    number: 55,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Cesium",
	    spectral_img: null,
	    symbol: "Cs",
	    xpos: 1,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		18,
		8,
		1
	    ]
	},
	{
	    name: "Barium",
	    appearance: null,
	    atomic_mass: 137.3277,
	    boil: 2118,
	    category: "alkaline earth metal",
	    color: null,
	    density: 3.51,
	    discovered_by: "Carl Wilhelm Scheele",
	    melt: 1000,
	    molar_heat: 28.07,
	    named_by: null,
	    number: 56,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Barium",
	    spectral_img: null,
	    symbol: "Ba",
	    xpos: 2,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		18,
		8,
		2
	    ]
	},
	{
	    name: "Lanthanum",
	    appearance: "silvery white",
	    atomic_mass: 138.905477,
	    boil: 3737,
	    category: "lanthanide",
	    color: null,
	    density: 6.162,
	    discovered_by: "Carl Gustaf Mosander",
	    melt: 1193,
	    molar_heat: 27.11,
	    named_by: null,
	    number: 57,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Lanthanum",
	    spectral_img: null,
	    symbol: "La",
	    xpos: 3,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		18,
		9,
		2
	    ]
	},
	{
	    name: "Cerium",
	    appearance: "silvery white",
	    atomic_mass: 140.1161,
	    boil: 3716,
	    category: "lanthanide",
	    color: null,
	    density: 6.77,
	    discovered_by: "Martin Heinrich Klaproth",
	    melt: 1068,
	    molar_heat: 26.94,
	    named_by: null,
	    number: 58,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Cerium",
	    spectral_img: null,
	    symbol: "Ce",
	    xpos: 4,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		19,
		9,
		2
	    ]
	},
	{
	    name: "Praseodymium",
	    appearance: "grayish white",
	    atomic_mass: 140.907662,
	    boil: 3403,
	    category: "lanthanide",
	    color: null,
	    density: 6.77,
	    discovered_by: "Carl Auer von Welsbach",
	    melt: 1208,
	    molar_heat: 27.2,
	    named_by: null,
	    number: 59,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Praseodymium",
	    spectral_img: null,
	    symbol: "Pr",
	    xpos: 5,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		21,
		8,
		2
	    ]
	},
	{
	    name: "Neodymium",
	    appearance: "silvery white",
	    atomic_mass: 144.2423,
	    boil: 3347,
	    category: "lanthanide",
	    color: null,
	    density: 7.01,
	    discovered_by: "Carl Auer von Welsbach",
	    melt: 1297,
	    molar_heat: 27.45,
	    named_by: null,
	    number: 60,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Neodymium",
	    spectral_img: null,
	    symbol: "Nd",
	    xpos: 6,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		22,
		8,
		2
	    ]
	},
	{
	    name: "Promethium",
	    appearance: "metallic",
	    atomic_mass: 145,
	    boil: 3273,
	    category: "lanthanide",
	    color: null,
	    density: 7.26,
	    discovered_by: "Chien Shiung Wu",
	    melt: 1315,
	    molar_heat: null,
	    named_by: "Isotopes of promethium",
	    number: 61,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Promethium",
	    spectral_img: null,
	    symbol: "Pm",
	    xpos: 7,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		23,
		8,
		2
	    ]
	},
	{
	    name: "Samarium",
	    appearance: "silvery white",
	    atomic_mass: 150.362,
	    boil: 2173,
	    category: "lanthanide",
	    color: null,
	    density: 7.52,
	    discovered_by: "Lecoq de Boisbaudran",
	    melt: 1345,
	    molar_heat: 29.54,
	    named_by: null,
	    number: 62,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Samarium",
	    spectral_img: null,
	    symbol: "Sm",
	    xpos: 8,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		24,
		8,
		2
	    ]
	},
	{
	    name: "Europium",
	    appearance: null,
	    atomic_mass: 151.9641,
	    boil: 1802,
	    category: "lanthanide",
	    color: null,
	    density: 5.264,
	    discovered_by: "Eugène-Anatole Demarçay",
	    melt: 1099,
	    molar_heat: 27.66,
	    named_by: null,
	    number: 63,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Europium",
	    spectral_img: null,
	    symbol: "Eu",
	    xpos: 9,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		25,
		8,
		2
	    ]
	},
	{
	    name: "Gadolinium",
	    appearance: "silvery white",
	    atomic_mass: 157.253,
	    boil: 3273,
	    category: "lanthanide",
	    color: null,
	    density: 7.9,
	    discovered_by: "Jean Charles Galissard de Marignac",
	    melt: 1585,
	    molar_heat: 37.03,
	    named_by: null,
	    number: 64,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Gadolinium",
	    spectral_img: null,
	    symbol: "Gd",
	    xpos: 10,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		25,
		9,
		2
	    ]
	},
	{
	    name: "Terbium",
	    appearance: "silvery white",
	    atomic_mass: 158.925352,
	    boil: 3396,
	    category: "lanthanide",
	    color: null,
	    density: 8.23,
	    discovered_by: "Carl Gustaf Mosander",
	    melt: 1629,
	    molar_heat: 28.91,
	    named_by: null,
	    number: 65,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Terbium",
	    spectral_img: null,
	    symbol: "Tb",
	    xpos: 11,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		27,
		8,
		2
	    ]
	},
	{
	    name: "Dysprosium",
	    appearance: "silvery white",
	    atomic_mass: 162.5001,
	    boil: 2840,
	    category: "lanthanide",
	    color: null,
	    density: 8.54,
	    discovered_by: "Lecoq de Boisbaudran",
	    melt: 1680,
	    molar_heat: 27.7,
	    named_by: null,
	    number: 66,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Dysprosium",
	    spectral_img: null,
	    symbol: "Dy",
	    xpos: 12,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		28,
		8,
		2
	    ]
	},
	{
	    name: "Holmium",
	    appearance: "silvery white",
	    atomic_mass: 164.930332,
	    boil: 2873,
	    category: "lanthanide",
	    color: null,
	    density: 8.79,
	    discovered_by: "Marc Delafontaine",
	    melt: 1734,
	    molar_heat: 27.15,
	    named_by: null,
	    number: 67,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Holmium",
	    spectral_img: null,
	    symbol: "Ho",
	    xpos: 13,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		29,
		8,
		2
	    ]
	},
	{
	    name: "Erbium",
	    appearance: "silvery white",
	    atomic_mass: 167.2593,
	    boil: 3141,
	    category: "lanthanide",
	    color: null,
	    density: 9.066,
	    discovered_by: "Carl Gustaf Mosander",
	    melt: 1802,
	    molar_heat: 28.12,
	    named_by: null,
	    number: 68,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Erbium",
	    spectral_img: null,
	    symbol: "Er",
	    xpos: 14,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		30,
		8,
		2
	    ]
	},
	{
	    name: "Thulium",
	    appearance: "silvery gray",
	    atomic_mass: 168.934222,
	    boil: 2223,
	    category: "lanthanide",
	    color: null,
	    density: 9.32,
	    discovered_by: "Per Teodor Cleve",
	    melt: 1818,
	    molar_heat: 27.03,
	    named_by: null,
	    number: 69,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Thulium",
	    spectral_img: null,
	    symbol: "Tm",
	    xpos: 15,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		31,
		8,
		2
	    ]
	},
	{
	    name: "Ytterbium",
	    appearance: null,
	    atomic_mass: 173.0451,
	    boil: 1469,
	    category: "lanthanide",
	    color: null,
	    density: 6.9,
	    discovered_by: "Jean Charles Galissard de Marignac",
	    melt: 1097,
	    molar_heat: 26.74,
	    named_by: null,
	    number: 70,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Ytterbium",
	    spectral_img: null,
	    symbol: "Yb",
	    xpos: 16,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		32,
		8,
		2
	    ]
	},
	{
	    name: "Lutetium",
	    appearance: "silvery white",
	    atomic_mass: 174.96681,
	    boil: 3675,
	    category: "lanthanide",
	    color: null,
	    density: 9.841,
	    discovered_by: "Georges Urbain",
	    melt: 1925,
	    molar_heat: 26.86,
	    named_by: null,
	    number: 71,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Lutetium",
	    spectral_img: null,
	    symbol: "Lu",
	    xpos: 17,
	    ypos: 9,
	    shells: [
		2,
		8,
		18,
		32,
		9,
		2
	    ]
	},
	{
	    name: "Hafnium",
	    appearance: "steel gray",
	    atomic_mass: 178.492,
	    boil: 4876,
	    category: "transition metal",
	    color: null,
	    density: 13.31,
	    discovered_by: "Dirk Coster",
	    melt: 2506,
	    molar_heat: 25.73,
	    named_by: null,
	    number: 72,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Hafnium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Hafnium_spectrum_visible.png",
	    symbol: "Hf",
	    xpos: 4,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		10,
		2
	    ]
	},
	{
	    name: "Tantalum",
	    appearance: "gray blue",
	    atomic_mass: 180.947882,
	    boil: 5731,
	    category: "transition metal",
	    color: null,
	    density: 16.69,
	    discovered_by: "Anders Gustaf Ekeberg",
	    melt: 3290,
	    molar_heat: 25.36,
	    named_by: null,
	    number: 73,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Tantalum",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Tantalum_spectrum_visible.png",
	    symbol: "Ta",
	    xpos: 5,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		11,
		2
	    ]
	},
	{
	    name: "Tungsten",
	    appearance: "grayish white, lustrous",
	    atomic_mass: 183.841,
	    boil: 6203,
	    category: "transition metal",
	    color: null,
	    density: 19.25,
	    discovered_by: "Carl Wilhelm Scheele",
	    melt: 3695,
	    molar_heat: 24.27,
	    named_by: null,
	    number: 74,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Tungsten",
	    spectral_img: null,
	    symbol: "W",
	    xpos: 6,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		12,
		2
	    ]
	},
	{
	    name: "Rhenium",
	    appearance: "silvery-grayish",
	    atomic_mass: 186.2071,
	    boil: 5869,
	    category: "transition metal",
	    color: null,
	    density: 21.02,
	    discovered_by: "Masataka Ogawa",
	    melt: 3459,
	    molar_heat: 25.48,
	    named_by: "Walter Noddack",
	    number: 75,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Rhenium",
	    spectral_img: null,
	    symbol: "Re",
	    xpos: 7,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		13,
		2
	    ]
	},
	{
	    name: "Osmium",
	    appearance: "silvery, blue cast",
	    atomic_mass: 190.233,
	    boil: 5285,
	    category: "transition metal",
	    color: null,
	    density: 22.59,
	    discovered_by: "Smithson Tennant",
	    melt: 3306,
	    molar_heat: 24.7,
	    named_by: null,
	    number: 76,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Osmium",
	    spectral_img: null,
	    symbol: "Os",
	    xpos: 8,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		14,
		2
	    ]
	},
	{
	    name: "Iridium",
	    appearance: "silvery white",
	    atomic_mass: 192.2173,
	    boil: 4403,
	    category: "transition metal",
	    color: null,
	    density: 22.56,
	    discovered_by: "Smithson Tennant",
	    melt: 2719,
	    molar_heat: 25.1,
	    named_by: null,
	    number: 77,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Iridium",
	    spectral_img: null,
	    symbol: "Ir",
	    xpos: 9,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		15,
		2
	    ]
	},
	{
	    name: "Platinum",
	    appearance: "silvery white",
	    atomic_mass: 195.0849,
	    boil: 4098,
	    category: "transition metal",
	    color: null,
	    density: 21.45,
	    discovered_by: "Antonio de Ulloa",
	    melt: 2041.4,
	    molar_heat: 25.86,
	    named_by: null,
	    number: 78,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Platinum",
	    spectral_img: null,
	    symbol: "Pt",
	    xpos: 10,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		17,
		1
	    ]
	},
	{
	    name: "Gold",
	    appearance: "metallic yellow",
	    atomic_mass: 196.9665695,
	    boil: 3243,
	    category: "transition metal",
	    color: null,
	    density: 19.3,
	    discovered_by: "Middle East",
	    melt: 1337.33,
	    molar_heat: 25.418,
	    named_by: null,
	    number: 79,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Gold",
	    spectral_img: null,
	    symbol: "Au",
	    xpos: 11,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		1
	    ]
	},
	{
	    name: "Mercury",
	    appearance: "silvery",
	    atomic_mass: 200.5923,
	    boil: 629.88,
	    category: "transition metal",
	    color: null,
	    density: 13.534,
	    discovered_by: "unknown, before 2000 BCE",
	    melt: 234.321,
	    molar_heat: 27.983,
	    named_by: null,
	    number: 80,
	    period: 6,
	    phase: "Liquid",
	    source: "https://en.wikipedia.org/wiki/Mercury (Element)",
	    spectral_img: null,
	    symbol: "Hg",
	    xpos: 12,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		2
	    ]
	},
	{
	    name: "Thallium",
	    appearance: "silvery white",
	    atomic_mass: 204.38,
	    boil: 1746,
	    category: "post-transition metal",
	    color: null,
	    density: 11.85,
	    discovered_by: "William Crookes",
	    melt: 577,
	    molar_heat: 26.32,
	    named_by: null,
	    number: 81,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Thallium",
	    spectral_img: null,
	    symbol: "Tl",
	    xpos: 13,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		3
	    ]
	},
	{
	    name: "Lead",
	    appearance: "metallic gray",
	    atomic_mass: 207.21,
	    boil: 2022,
	    category: "post-transition metal",
	    color: null,
	    density: 11.34,
	    discovered_by: "Middle East",
	    melt: 600.61,
	    molar_heat: 26.65,
	    named_by: null,
	    number: 82,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Lead_(element)",
	    spectral_img: null,
	    symbol: "Pb",
	    xpos: 14,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		4
	    ]
	},
	{
	    name: "Bismuth",
	    appearance: "lustrous silver",
	    atomic_mass: 208.980401,
	    boil: 1837,
	    category: "post-transition metal",
	    color: null,
	    density: 9.78,
	    discovered_by: "Claude François Geoffroy",
	    melt: 544.7,
	    molar_heat: 25.52,
	    named_by: null,
	    number: 83,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Bismuth",
	    spectral_img: null,
	    symbol: "Bi",
	    xpos: 15,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		5
	    ]
	},
	{
	    name: "Polonium",
	    appearance: "silvery",
	    atomic_mass: 209,
	    boil: 1235,
	    category: "post-transition metal",
	    color: null,
	    density: 9.196,
	    discovered_by: "Pierre Curie",
	    melt: 527,
	    molar_heat: 26.4,
	    named_by: null,
	    number: 84,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Polonium",
	    spectral_img: null,
	    symbol: "Po",
	    xpos: 16,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		6
	    ]
	},
	{
	    name: "Astatine",
	    appearance: "unknown, probably metallic",
	    atomic_mass: 210,
	    boil: 610,
	    category: "metalloid",
	    color: null,
	    density: 6.35,
	    discovered_by: "Dale R. Corson",
	    melt: 575,
	    molar_heat: null,
	    named_by: null,
	    number: 85,
	    period: 6,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Astatine",
	    spectral_img: null,
	    symbol: "At",
	    xpos: 17,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		7
	    ]
	},
	{
	    name: "Radon",
	    appearance: "colorless gas, occasionally glows green or red in discharge tubes",
	    atomic_mass: 222,
	    boil: 211.5,
	    category: "noble gas",
	    color: null,
	    density: 9.73,
	    discovered_by: "Friedrich Ernst Dorn",
	    melt: 202,
	    molar_heat: null,
	    named_by: null,
	    number: 86,
	    period: 6,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Radon",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Radon_spectrum.png",
	    symbol: "Rn",
	    xpos: 18,
	    ypos: 6,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		8
	    ]
	},
	{
	    name: "Francium",
	    appearance: null,
	    atomic_mass: 223,
	    boil: 950,
	    category: "alkali",
	    color: null,
	    density: 1.87,
	    discovered_by: "Marguerite Perey",
	    melt: 300,
	    molar_heat: null,
	    named_by: null,
	    number: 87,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Francium",
	    spectral_img: null,
	    symbol: "Fr",
	    xpos: 1,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		8,
		1
	    ]
	},
	{
	    name: "Radium",
	    appearance: "silvery white metallic",
	    atomic_mass: 226,
	    boil: 2010,
	    category: "alkaline earth metal",
	    color: null,
	    density: 5.5,
	    discovered_by: "Pierre Curie",
	    melt: 1233,
	    molar_heat: null,
	    named_by: null,
	    number: 88,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Radium",
	    spectral_img: null,
	    symbol: "Ra",
	    xpos: 2,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		8,
		2
	    ]
	},
	{
	    name: "Actinium",
	    appearance: null,
	    atomic_mass: 227,
	    boil: 3500,
	    category: "actinide",
	    color: null,
	    density: 10,
	    discovered_by: "Friedrich Oskar Giesel",
	    melt: 1500,
	    molar_heat: 27.2,
	    named_by: null,
	    number: 89,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Actinium",
	    spectral_img: null,
	    symbol: "Ac",
	    xpos: 3,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		9,
		2
	    ]
	},
	{
	    name: "Thorium",
	    appearance: "silvery, often with black tarnish",
	    atomic_mass: 232.03774,
	    boil: 5061,
	    category: "actinide",
	    color: null,
	    density: 11.724,
	    discovered_by: "Jöns Jakob Berzelius",
	    melt: 2023,
	    molar_heat: 26.23,
	    named_by: null,
	    number: 90,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Thorium",
	    spectral_img: null,
	    symbol: "Th",
	    xpos: 4,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		18,
		10,
		2
	    ]
	},
	{
	    name: "Protactinium",
	    appearance: "bright, silvery metallic luster",
	    atomic_mass: 231.035882,
	    boil: 4300,
	    category: "actinide",
	    color: null,
	    density: 15.37,
	    discovered_by: "William Crookes",
	    melt: 1841,
	    molar_heat: null,
	    named_by: "Otto Hahn",
	    number: 91,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Protactinium",
	    spectral_img: null,
	    symbol: "Pa",
	    xpos: 5,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		20,
		9,
		2
	    ]
	},
	{
	    name: "Uranium",
	    appearance: null,
	    atomic_mass: 238.028913,
	    boil: 4404,
	    category: "actinide",
	    color: null,
	    density: 19.1,
	    discovered_by: "Martin Heinrich Klaproth",
	    melt: 1405.3,
	    molar_heat: 27.665,
	    named_by: null,
	    number: 92,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Uranium",
	    spectral_img: null,
	    symbol: "U",
	    xpos: 6,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		21,
		9,
		2
	    ]
	},
	{
	    name: "Neptunium",
	    appearance: "silvery metallic",
	    atomic_mass: 237,
	    boil: 4447,
	    category: "actinide",
	    color: null,
	    density: 20.45,
	    discovered_by: "Edwin McMillan",
	    melt: 912,
	    molar_heat: 29.46,
	    named_by: null,
	    number: 93,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Neptunium",
	    spectral_img: null,
	    symbol: "Np",
	    xpos: 7,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		22,
		9,
		2
	    ]
	},
	{
	    name: "Plutonium",
	    appearance: "silvery white, tarnishing to dark gray in air",
	    atomic_mass: 244,
	    boil: 3505,
	    category: "actinide",
	    color: null,
	    density: 19.816,
	    discovered_by: "Glenn T. Seaborg",
	    melt: 912.5,
	    molar_heat: 35.5,
	    named_by: null,
	    number: 94,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Plutonium",
	    spectral_img: null,
	    symbol: "Pu",
	    xpos: 8,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		24,
		8,
		2
	    ]
	},
	{
	    name: "Americium",
	    appearance: "silvery white",
	    atomic_mass: 243,
	    boil: 2880,
	    category: "actinide",
	    color: null,
	    density: 12,
	    discovered_by: "Glenn T. Seaborg",
	    melt: 1449,
	    molar_heat: 62.7,
	    named_by: null,
	    number: 95,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Americium",
	    spectral_img: "https://en.wikipedia.org/wiki/File:Americium_spectrum_visible.png",
	    symbol: "Am",
	    xpos: 9,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		25,
		8,
		2
	    ]
	},
	{
	    name: "Curium",
	    appearance: "silvery metallic, glows purple in the dark",
	    atomic_mass: 247,
	    boil: 3383,
	    category: "actinide",
	    color: null,
	    density: 13.51,
	    discovered_by: "Glenn T. Seaborg",
	    melt: 1613,
	    molar_heat: null,
	    named_by: null,
	    number: 96,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Curium",
	    spectral_img: null,
	    symbol: "Cm",
	    xpos: 10,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		25,
		9,
		2
	    ]
	},
	{
	    name: "Berkelium",
	    appearance: "silvery",
	    atomic_mass: 247,
	    boil: 2900,
	    category: "actinide",
	    color: null,
	    density: 14.78,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: 1259,
	    molar_heat: null,
	    named_by: null,
	    number: 97,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Berkelium",
	    spectral_img: null,
	    symbol: "Bk",
	    xpos: 11,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		27,
		8,
		2
	    ]
	},
	{
	    name: "Californium",
	    appearance: "silvery",
	    atomic_mass: 251,
	    boil: 1743,
	    category: "actinide",
	    color: null,
	    density: 15.1,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: 1173,
	    molar_heat: null,
	    named_by: null,
	    number: 98,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Californium",
	    spectral_img: null,
	    symbol: "Cf",
	    xpos: 12,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		28,
		8,
		2
	    ]
	},
	{
	    name: "Einsteinium",
	    appearance: "silver-colored",
	    atomic_mass: 252,
	    boil: 1269,
	    category: "actinide",
	    color: null,
	    density: 8.84,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: 1133,
	    molar_heat: null,
	    named_by: null,
	    number: 99,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Einsteinium",
	    spectral_img: null,
	    symbol: "Es",
	    xpos: 13,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		29,
		8,
		2
	    ]
	},
	{
	    name: "Fermium",
	    appearance: null,
	    atomic_mass: 257,
	    boil: null,
	    category: "actinide",
	    color: null,
	    density: null,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: 1800,
	    molar_heat: null,
	    named_by: null,
	    number: 100,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Fermium",
	    spectral_img: null,
	    symbol: "Fm",
	    xpos: 14,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		30,
		8,
		2
	    ]
	},
	{
	    name: "Mendelevium",
	    appearance: null,
	    atomic_mass: 258,
	    boil: null,
	    category: "actinide",
	    color: null,
	    density: null,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: 1100,
	    molar_heat: null,
	    named_by: null,
	    number: 101,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Mendelevium",
	    spectral_img: null,
	    symbol: "Md",
	    xpos: 15,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		31,
		8,
		2
	    ]
	},
	{
	    name: "Nobelium",
	    appearance: null,
	    atomic_mass: 259,
	    boil: null,
	    category: "actinide",
	    color: null,
	    density: null,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: 1100,
	    molar_heat: null,
	    named_by: null,
	    number: 102,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Nobelium",
	    spectral_img: null,
	    symbol: "No",
	    xpos: 16,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		8,
		2
	    ]
	},
	{
	    name: "Lawrencium",
	    appearance: null,
	    atomic_mass: 266,
	    boil: null,
	    category: "actinide",
	    color: null,
	    density: null,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: 1900,
	    molar_heat: null,
	    named_by: null,
	    number: 103,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Lawrencium",
	    spectral_img: null,
	    symbol: "Lr",
	    xpos: 17,
	    ypos: 10,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		8,
		3
	    ]
	},
	{
	    name: "Rutherfordium",
	    appearance: null,
	    atomic_mass: 267,
	    boil: 5800,
	    category: "transition metal",
	    color: null,
	    density: 23.2,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: 2400,
	    molar_heat: null,
	    named_by: null,
	    number: 104,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Rutherfordium",
	    spectral_img: null,
	    symbol: "Rf",
	    xpos: 4,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		10,
		2
	    ]
	},
	{
	    name: "Dubnium",
	    appearance: null,
	    atomic_mass: 268,
	    boil: null,
	    category: "transition metal",
	    color: null,
	    density: 29.3,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 105,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Dubnium",
	    spectral_img: null,
	    symbol: "Db",
	    xpos: 5,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		11,
		2
	    ]
	},
	{
	    name: "Seaborgium",
	    appearance: null,
	    atomic_mass: 269,
	    boil: null,
	    category: "transition metal",
	    color: null,
	    density: 35,
	    discovered_by: "Lawrence Berkeley National Laboratory",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 106,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Seaborgium",
	    spectral_img: null,
	    symbol: "Sg",
	    xpos: 6,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		12,
		2
	    ]
	},
	{
	    name: "Bohrium",
	    appearance: null,
	    atomic_mass: 270,
	    boil: null,
	    category: "transition metal",
	    color: null,
	    density: 37.1,
	    discovered_by: "Gesellschaft für Schwerionenforschung",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 107,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Bohrium",
	    spectral_img: null,
	    symbol: "Bh",
	    xpos: 7,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		13,
		2
	    ]
	},
	{
	    name: "Hassium",
	    appearance: null,
	    atomic_mass: 269,
	    boil: null,
	    category: "transition metal",
	    color: null,
	    density: 40.7,
	    discovered_by: "Gesellschaft für Schwerionenforschung",
	    melt: 126,
	    molar_heat: null,
	    named_by: null,
	    number: 108,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Hassium",
	    spectral_img: null,
	    symbol: "Hs",
	    xpos: 8,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		14,
		2
	    ]
	},
	{
	    name: "Meitnerium",
	    appearance: null,
	    atomic_mass: 278,
	    boil: null,
	    category: "unknown, probably transition metal",
	    color: null,
	    density: 37.4,
	    discovered_by: "Gesellschaft für Schwerionenforschung",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 109,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Meitnerium",
	    spectral_img: null,
	    symbol: "Mt",
	    xpos: 9,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		15,
		2
	    ]
	},
	{
	    name: "Darmstadtium",
	    appearance: null,
	    atomic_mass: 281,
	    boil: null,
	    category: "unknown, probably transition metal",
	    color: null,
	    density: 34.8,
	    discovered_by: "Gesellschaft für Schwerionenforschung",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 110,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Darmstadtium",
	    spectral_img: null,
	    symbol: "Ds",
	    xpos: 10,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		16,
		2
	    ]
	},
	{
	    name: "Roentgenium",
	    appearance: null,
	    atomic_mass: 282,
	    boil: null,
	    category: "unknown, probably transition metal",
	    color: null,
	    density: 28.7,
	    discovered_by: "Gesellschaft für Schwerionenforschung",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 111,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Roentgenium",
	    spectral_img: null,
	    symbol: "Rg",
	    xpos: 11,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		17,
		2
	    ]
	},
	{
	    name: "Copernicium",
	    appearance: null,
	    atomic_mass: 285,
	    boil: 3570,
	    category: "transition metal",
	    color: null,
	    density: 23.7,
	    discovered_by: "Gesellschaft für Schwerionenforschung",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 112,
	    period: 7,
	    phase: "Gas",
	    source: "https://en.wikipedia.org/wiki/Copernicium",
	    spectral_img: null,
	    symbol: "Cn",
	    xpos: 12,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		2
	    ]
	},
	{
	    name: "Nihonium",
	    appearance: null,
	    atomic_mass: 286,
	    boil: 1430,
	    category: "unknown, probably transition metal",
	    color: null,
	    density: 16,
	    discovered_by: "RIKEN",
	    melt: 700,
	    molar_heat: null,
	    named_by: null,
	    number: 113,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Ununtrium",
	    spectral_img: null,
	    symbol: "Nh",
	    xpos: 13,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		3
	    ]
	},
	{
	    name: "Flerovium",
	    appearance: null,
	    atomic_mass: 289,
	    boil: 420,
	    category: "post-transition metal",
	    color: null,
	    density: 14,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: 340,
	    molar_heat: null,
	    named_by: null,
	    number: 114,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Flerovium",
	    spectral_img: null,
	    symbol: "Fl",
	    xpos: 14,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		4
	    ]
	},
	{
	    name: "Moscovium",
	    appearance: null,
	    atomic_mass: 289,
	    boil: 1400,
	    category: "unknown, probably post-transition metal",
	    color: null,
	    density: 13.5,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: 670,
	    molar_heat: null,
	    named_by: null,
	    number: 115,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Ununpentium",
	    spectral_img: null,
	    symbol: "Mc",
	    xpos: 15,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		5
	    ]
	},
	{
	    name: "Livermorium",
	    appearance: null,
	    atomic_mass: 293,
	    boil: 1085,
	    category: "unknown, probably post-transition metal",
	    color: null,
	    density: 12.9,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: 709,
	    molar_heat: null,
	    named_by: null,
	    number: 116,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Livermorium",
	    spectral_img: null,
	    symbol: "Lv",
	    xpos: 16,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		6
	    ]
	},
	{
	    name: "Tennessine",
	    appearance: null,
	    atomic_mass: 294,
	    boil: 883,
	    category: "unknown, probably metalloid",
	    color: null,
	    density: 7.17,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: 723,
	    molar_heat: null,
	    named_by: null,
	    number: 117,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Tennessine",
	    spectral_img: null,
	    symbol: "Ts",
	    xpos: 17,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		7
	    ]
	},
	{
	    name: "Oganesson",
	    appearance: null,
	    atomic_mass: 294,
	    boil: 350,
	    category: "unknown, predicted to be noble gas",
	    color: null,
	    density: 4.95,
	    discovered_by: "Joint Institute for Nuclear Research",
	    melt: null,
	    molar_heat: null,
	    named_by: null,
	    number: 118,
	    period: 7,
	    phase: "Solid",
	    source: "https://en.wikipedia.org/wiki/Oganesson",
	    spectral_img: null,
	    symbol: "Og",
	    xpos: 18,
	    ypos: 7,
	    shells: [
		2,
		8,
		18,
		32,
		32,
		18,
		8
	    ]
	}
    ]
}
